import type { Product } from '@/types'

// Usado como fallback quando Supabase não está configurado
export const LOCAL_PRODUCTS: Product[] = [
  { id: 1,  name: 'Caldo de Carne',      category: 'temperos', tag: 'Caldo',      description: 'Carne e gordura bovina, sal, especiarias, amido de milho, realçador de sabor, corantes e conservantes.', weight: '60g', price: 8.90, image_url: '/images/caldo-carne.jpg',     is_new: false, is_sale: false },
  { id: 2,  name: 'Páprica Defumada',    category: 'temperos', tag: 'Defumado',   description: 'Obtida de pimentões vermelhos secos e defumados. Confere sabor e aroma característico a diversos pratos.', weight: '50g', price: 7.90, image_url: '/images/paprica-defumada.jpg', is_new: true,  is_sale: false },
  { id: 3,  name: 'Bicarbonato de Sódio',category: 'temperos', tag: 'Culinário',  description: 'Multiuso na cozinha: fermento natural em bolos, neutralizador de acidez e amaciante de carnes.', weight: '70g', price: 6.90, image_url: '/images/bicarbonato.jpg',         is_new: false, is_sale: false },
  { id: 4,  name: 'Colorau (Urucum)',    category: 'temperos', tag: 'Colorífico', description: 'Milho, óleo de soja e urucum. Sem glúten, sem lactose. Corante natural para dar aquela cor especial.', weight: '50g', price: 5.90, image_url: '/images/colorau.jpg',            is_new: false, is_sale: false },
  { id: 5,  name: 'Lemon Pepper',        category: 'temperos', tag: 'Blend',      description: 'Sal, açafrão, cebola granulada, pimenta do reino, coentro e ácido cítrico. Perfeito para frango e peixes.', weight: '50g', price: 8.90, image_url: '/images/lemon-pepper.jpg',   is_new: false, is_sale: false },
  { id: 6,  name: 'Páprica Doce',        category: 'temperos', tag: 'Suave',      description: 'Proveniente de pimentões macerados, maduros e dessecados. Ótima em peixes, aves, batata e molhos.', weight: '50g', price: 7.90, image_url: '/images/paprica-doce.jpg',       is_new: false, is_sale: false },
  { id: 7,  name: 'Páprica Picante',     category: 'temperos', tag: 'Picante',    description: 'Pimentões secos e moídos, pimenta, farinha de milho e urucum. Para quem gosta de ardência.', weight: '50g', price: 7.90, image_url: '/images/paprica-picante.jpg',   is_new: false, is_sale: false },
  { id: 8,  name: 'Tempero Edu Guedes',  category: 'temperos', tag: 'Especial',   description: 'Sal, cebola, cenoura, pimentão, açafrão, salsa, cebolinha, amido de milho, orégano e aroma de costela.', weight: '50g', price: 9.90, image_url: '/images/edu-guedes.jpg',    is_new: true,  is_sale: false },
  { id: 9,  name: 'Chimichurri',         category: 'temperos', tag: 'Churrasco',  description: 'Cebola, alho, salsa, pimentão, orégano, cebolinha, mostarda, tomate, manjericão, louro e noz moscada.', weight: '50g', price: 9.90, image_url: '/images/chimichurri.jpg',    is_new: false, is_sale: false },
  { id: 10, name: 'Amaciante de Carne',  category: 'temperos', tag: 'Amaciante',  description: 'Sal, alho pó, cebola pó, pimenta, salsa e glutamato monossódico. Deixa sua carne macia e saborosa.', weight: '60g', price: 8.90, image_url: '/images/amaciante-carne.jpg',  is_new: false, is_sale: false },
  { id: 11, name: 'Orégano',             category: 'temperos', tag: 'Erva',       description: 'Erva aromática com sabor intenso e picante, com notas de menta e limão. Ideal para pizzas e massas.', weight: '20g', price: 4.90, image_url: '/images/oregano.jpg',           is_new: false, is_sale: false },
  { id: 12, name: 'Açafrão da Terra',    category: 'temperos', tag: 'Colorífico', description: 'Amido de milho, Açafrão da Terra e óleo vegetal. Popular na culinária indiana e em diversas cozinhas.', weight: '50g', price: 7.90, image_url: '/images/acafrao.jpg',         is_new: false, is_sale: false },
  { id: 13, name: 'Caldo de Galinha',    category: 'temperos', tag: 'Caldo',      description: 'Carne e gordura de galinha, sal, especiarias, amido de milho, realçador de sabor e conservantes.', weight: '60g', price: 8.90, image_url: '/images/caldo-galinha.jpg',     is_new: false, is_sale: false },
  { id: 14, name: 'Tempero Ana Maria',   category: 'temperos', tag: 'Especial',   description: 'Alho frito, alho granulado, cebola desidratada, manjericão, manjerona, orégano, pimentão, salsa e tomilho.', weight: '50g', price: 9.90, image_url: '/images/ana-maria.jpg', is_new: true,  is_sale: false },
]
